<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="Madhulita Sarangi" lastModifiedBy="Madhulita Sarangi" checksumTest="true" creationDate="27/04/2023 22:36:08 +0530" engineType="DML" lastModifiedDate="27/04/2023 22:39:51 +0530" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/Test.dmlflw"/>
   </mappingInformations>
</project>